---
- name: Setup WSL Environment
  hosts: wsl
  become: true
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600




    - name: Install Node.js (via NVM)
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
      args:
        executable: /bin/bash

    - name: Install Docker (optional)
      shell: |
        apt-get remove docker docker-engine docker.io containerd runc -y
        apt-get update
        apt-get install apt-transport-https ca-certificates curl software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install docker-ce docker-ce-cli containerd.io -y
      args:
        executable: /bin/bash

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Clean up
      apt:
        autoclean: yes
        autoremove: yes
