- name: Update and upgrade APT packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - curl
      - git
      - zsh
      - build-essential
      - python3-pip
      - jq
      - unzip
    state: present


- name: Set Git user name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Set Git user email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global

- name: Install AWS CLI v2
  become: yes
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
    unzip /tmp/awscliv2.zip -d /tmp
    /tmp/aws/install
  args:
    executable: /bin/bash